# Generated by Django 4.2.13 on 2024-07-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
