# Generated by Django 4.2.13 on 2024-07-29 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_reservation_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favourited',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
